id: IEBA26DEC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T10:58:19+00:00'
last_modified: '2022-06-07T18:21:31.577955+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22345
  title: གསུང་འབུམ། བློ་བཟང་བསྟན་པའི་རྒྱལ་མཚན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EAAD:
      image_group_id: I1KG977
      title: ''
      total_pages: 470
      order: 1
      base_file: EAAD.txt
    DF56:
      image_group_id: I1KG978
      title: ''
      total_pages: 348
      order: 2
      base_file: DF56.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
