id: P003200
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22345
  title: གསུང་འབུམ། བློ་བཟང་བསྟན་པའི་རྒྱལ་མཚན
  author: ''
  volumes:
    4d5666ae54ef49c79bd3c1447847b2a4:
      image_group_id: I1KG977
      title: ''
      volume_number: 1
      total_pages: 470
      base_file: v001.txt
    6debc3bff09b47eba0e111049fa334e4:
      image_group_id: I1KG978
      title: ''
      volume_number: 2
      total_pages: 348
      base_file: v002.txt
